---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: StorageBlobService
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: StorageBlobService
          image: pdecontainerregistry.azurecr.io/StorageBlobService:Latest
          ports:
            - containerPort: 8081

 kind: Service 
 apiVersion: v1 
 metadata: 
   name: StorageBlobService
 spec: 
   selector: 
     app: web 
   ports: 
   - protocol: TCP 
     port: 8081 
     targetPort: 8081 
   type: LoadBalancer